### ISSUE TITLE
EXC_BAD_ACCESS at setAlpnProtocols

### ISSUE THREAD

**Issue by ghost** [Jamol/Nutil#1]
Hi. I'm trying to send a http2 request using NutilAPI. This is my code: 
```swift
let request = NutilFactory.createRequest("HTTP/2.0")
_ = request?.onData({
    (data, len) -> Void in
    print(String(data: Data(bytes: data, count: len), encoding: .utf8))
}).sendRequest("GET", "https://http2.golang.org/reqinfo")
```
Then a EXC_BAD_ACCESS occurs at function setAlpnProtocols (SslHandler.swift, line 44). It turns out that `ssl` in this function is nil. Is this the correct way to make a http2 request? Or did I miss something?

**Comment by Jamol** [comment]
Thank you for reporting issue.
the cert verification was failed and ssl was nil, but there was no null pointer protection on setAlpnProtocols

**Comment by Jamol** [comment]
and also you need add the CA certs to /path to your executable/cert/ca.cer, otherwise the cert verification will fail

**Comment by ghost** [comment]
Thanks a lot! The connection has been successfully set up with some minor changes to your code. I created a pull request and hope you'll find something useful. Since I'm not quite familiar with OpenSSL, there may be mistakes and please correct them. :-)
